apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-platform.backendFullname" . }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http

