global:
  baseDomain: localtest.me
  storageClassName: ""

dashboard:
  image:
    repository: myuser/store-platform-dashboard
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    host: dashboard.localtest.me

backend:
  image:
    repository: myuser/store-platform-backend
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  ingress:
    enabled: true
    className: nginx
    host: api.localtest.me

