global:
  baseDomain: localtest.me
  storageClassName: ""

dashboard:
  image:
    repository: dthanisha/store-platform-dashboard
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    host: dashboard.localtest.me

backend:
  image:
    repository: dthanisha/store-platform-backend
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  ingress:
    enabled: true
    className: nginx
    host: api.localtest.me
  medusaImages:
    api: "medusajs/medusa:latest"
    storefront: "medusajs/storefront:latest"
    postgres: "postgres:15-alpine"
  env:
    MAX_STORES: "100"
    PROVISIONING_TIMEOUT_MINUTES: "10"
